[project]
name = "blog"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "itables>=2.5.2",
    "jupyter>=1.1.1",
    "plotly>=6.5.0",
    "pyyaml>=6.0.3",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
